stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - pip3 install --upgrade pip
        - python calculator_form.py
        - python calculator.py

test:
    stage: test
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python unittest_cal_form.py