stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script:
        - echo "Building"
        - pip3 install --upgrade pip
        - pip install -r requirements.txt
        - python3 app/calculator.py
        - python3 app/calculator_form.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - pip install -r requirements.txt
        - coverage run -m unittest_cal
        - coverage run -m unittest_cal_form
        - coverage report
        - coverage html
